### ISSUE TITLE
rucaptcha :: возвращать CAPTCHA_ID

### ISSUE THREAD

**Issue by stdex** [lorien/captcha_solver#10]
В FAQ есть метод reportbad: https://rucaptcha.com/support/faq/44/
Но т.к. там требуется CAPTCHA_ID, который нигде не возвращается, то это сделать нельзя.

**Comment by lorien** [comment]
Captcha Solver library is deprecated. Check out my new library decaptcher: https://github.com/lorien/decaptcher
Read README, there is example of how to get CAPTCHA_ID.
Be aware, this is quite young project. It is age is 1 day (on Mar 08, 2019) :)
Feedback is welcome.
